# can interface name as shown in ifconfig -a
can_device: "can0"
# can bridge receive topic
can_rx_topic: "/can/received_messages"
# can bridge transmit topic
can_tx_ropic: "/can/sent_messages"
# axis state update in Hz
update_rate: 200
# engage axises on startup
engage_on_startup: true
# disengage axises on shutdown
disengage_on_shutdown: true
# minimum axis velocity - e.g if set to 1.0 target velocity will be set to this value
# for both positive and negative velocities (0.5 will become 1.0, -0.5 will become -1.0)
axis_min_velocity: 0.0
# array of strings representing names of axises
axis_names: ["left_hip_AA", "left_hip_FE", "left_knee", "right_hip_AA", "right_hip_FE", "right_knee"]
# array of ints representing can ids of axises
axis_can_ids: [1, 2, 3, 4, 5, 6]
# array of axis directions
axis_directions: ["forward", "forward", "forward", "forward", "forward", "forward"]
